blogs/urls.py
"""
URLS - FOR Blogs App
Urls - call the functions in views.py. Views functions contain logic regd. what to send as response.

"""

from django.urls import path
from . import views  # importing views.py from current directory(hence used '.')

app_name = 'blogs'

urlpatterns = [
    path('', views.blogs_list, name='blogs_list'),
    path('create/', views.blog_create, name='blog_create'),
    path('drafts/', views.drafts_list, name='drafts_list'),
    path('load_draft/', views.load_draft, name='load_draft'),

    path('recently_viewed/', views.recently_viewed_blogs, name='recently_viewed_blogs'),
    # below regex: slug can be any character(word, number etc), also includes'-' and length is nolimit.
    path('<slug:slug>/', views.blog_detail, name='blog_detail'),
    path('<slug:slug>/like/', views.like_post, name='like_post'),

]

events/urls.py
# events/urls.py
from django.urls import path
from . import views

app_name = 'events'

urlpatterns = [
    path('add_event/', views.add_event, name='add_event'),
    path('enroll_event/', views.enroll_event, name='enroll_event'),
    path('unenroll_event/', views.unenroll_event, name='unenroll_event'),
    path('my_events/', views.my_events, name='my_events'),
    path('', views.events_list, name='events_list'),
]

gread/urls.py
"""
URLS - FOR Base App - Gread.com
Urls - call the functions in views.py. Views functions contain logic regd. what to send as response.

"""

from django.contrib import admin
from django.urls import path, include  # here include is used to include other urls (from apps)
from . import views  # importing views.py from current directory(hence used '.')
from blogs import views as blogs_views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns  #for loading static files
from django.conf.urls.static import static  #For media Files
from django.conf import settings  #importing all vars and functions from settins.py file
from accounts.admin_site import custom_admin_site

urlpatterns = [
    path('', views.homepage, name='home'),
    # path('', blogs_views.blogs_list, name='home'),
    path('admin/', admin.site.urls),
    # path('admin/', custom_admin_site.urls),
    path('about/', views.about, name='about'),

    # We need to register urls for other apps here in the base urls.py, in order to access them
    path('blogs/', include('blogs.urls')),
    path('accounts/', include('accounts.urls')),
    path("accounts/", include("django.contrib.auth.urls")),
    path('events/', include('events.urls')),

    #     Test Urls
    path('index/', views.index, name='index'),
    path('contact/', views.contact, name='contact'),

]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

events/models.py
# models.py
from django.db import models
from django.contrib.auth.models import User


class Event(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    description = models.TextField()
    datetime = models.DateTimeField(null=True, blank=True)  # Allow null and blank values
    location = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    enrollment_limit = models.PositiveIntegerField()
    enrolled_users = models.ManyToManyField(User, related_name='enrolled_events', blank=True)
    additional_details = models.TextField(blank=True)
    contact_information = models.CharField(max_length=255, blank=True)
    event_banner = models.ImageField(default='default.png', blank=True, null=True)

    def __str__(self):
        return self.title

    def is_full(self):
        return self.enrolled_users.count() >= self.enrollment_limit

    def shorter_description(self):
        return self.description[:90] + "..."

events/forms.py
# forms.py
from django import forms
from .models import Event


class EventForm(forms.ModelForm):
    datetime = forms.DateTimeField(widget=forms.DateTimeInput(attrs={'type': 'datetime-local'}))

    class Meta:
        model = Event
        fields = ['title', 'description', 'datetime', 'location', 'enrollment_limit', 'additional_details',
                  'contact_information', 'event_banner']


class EnrollmentForm(forms.Form):
    event_id = forms.IntegerField(widget=forms.HiddenInput)

events/views.py
# views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from .models import Event
from .forms import EventForm, EnrollmentForm


@login_required
def add_event(request):
    if request.method == 'POST':
        form = EventForm(request.POST, request.FILES)
        if form.is_valid():
            event = form.save(commit=False)
            event.author = request.user
            event.save()
            return redirect('events:events_list')
    else:
        form = EventForm()
    return render(request, 'events/add_event.html', {'form': form})


@login_required
def enroll_event(request):
    if request.method == 'POST':
        form = EnrollmentForm(request.POST)
        if form.is_valid():
            event_id = form.cleaned_data['event_id']
            event = get_object_or_404(Event, id=event_id)
            if not event.is_full():
                event.enrolled_users.add(request.user)
                return redirect('events:events_list')
    return redirect('events:events_list')


@login_required
def unenroll_event(request):
    if request.method == 'POST':
        form = EnrollmentForm(request.POST)
        if form.is_valid():
            event_id = form.cleaned_data['event_id']
            event = get_object_or_404(Event, id=event_id)
            if request.user in event.enrolled_users.all():
                event.enrolled_users.remove(request.user)
                return redirect('events:events_list')
    return redirect('events:events_list')


def events_list(request):
    events = Event.objects.all().order_by('-datetime')
    return render(request, 'events/events_list.html', {'events': events})


@login_required
def my_events(request):
    user = request.user
    events = user.enrolled_events.all().order_by('-datetime')
    return render(request, 'events/my_events.html', {'events': events})

events/templates/events/add_event.html
{% extends 'base_layout.html' %}
{% load static %}
{% block title %} Gread - Add Event {% endblock %}
{% block content %}
<section class="contact-section section-padding" style="padding-top: 200px">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-12 mx-auto">
                <div class="section-title-wrap mb-5">
                    <h4 class="section-title">Add Event</h4>
                </div>

                <form method="post" class="custom-form contact-form" enctype="multipart/form-data" role="form">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-lg-12 col-md-12 col-12 mb-3">
                            <div class="form-floating">
                                <input type="text" name="title" id="id_title" class="form-control" placeholder="Title" value="{{ form.title.value|default_if_none:'' }}">
                                <label for="id_title">Title</label>
                                {% if form.title.errors %}
                                    <div class="invalid-feedback d-block">
                                        {{ form.title.errors }}
                                    </div>
                                {% endif %}
                            </div>
                        </div>

                        <div class="col-lg-12 col-md-12 col-12 mb-3">
                            <div class="form-floating">
                                <textarea name="description" id="id_description" class="form-control" placeholder="Description">{{ form.description.value|default_if_none:'' }}</textarea>
                                <label for="id_description">Description</label>
                                {% if form.description.errors %}
                                    <div class="invalid-feedback d-block">
                                        {{ form.description.errors }}
                                    </div>
                                {% endif %}
                            </div>
                        </div>

                        <div class="col-lg-12 col-md-12 col-12 mb-3">
                            <div class="form-floating">
                                <input type="datetime-local" name="datetime" id="id_datetime" class="form-control" placeholder="Date and Time" value="{{ form.datetime.value|default_if_none:'' }}">
                                <label for="id_datetime">Date and Time</label>
                                {% if form.datetime.errors %}
                                    <div class="invalid-feedback d-block">
                                        {{ form.datetime.errors }}
                                    </div>
                                {% endif %}
                            </div>
                        </div>

                        <div class="col-lg-12 col-md-12 col-12 mb-3">
                            <div class="form-floating">
                                <input type="text" name="location" id="id_location" class="form-control" placeholder="Location" value="{{ form.location.value|default_if_none:'' }}">
                                <label for="id_location">Location</label>
                                {% if form.location.errors %}
                                    <div class="invalid-feedback d-block">
                                        {{ form.location.errors }}
                                    </div>
                                {% endif %}
                            </div>
                        </div>

                        <div class="col-lg-12 col-md-12 col-12 mb-3">
                            <div class="form-floating">
                                <input type="number" name="enrollment_limit" id="id_enrollment_limit" class="form-control" placeholder="Enrollment Limit" value="{{ form.enrollment_limit.value|default_if_none:'' }}">
                                <label for="id_enrollment_limit">Enrollment Limit</label>
                                {% if form.enrollment_limit.errors %}
                                    <div class="invalid-feedback d-block">
                                        {{ form.enrollment_limit.errors }}
                                    </div>
                                {% endif %}
                            </div>
                        </div>

                        <div class="col-lg-12 col-md-12 col-12 mb-3">
                            <div class="form-floating">
                                <textarea name="additional_details" id="id_additional_details" class="form-control" placeholder="Additional Details">{{ form.additional_details.value|default_if_none:'' }}</textarea>
                                <label for="id_additional_details">Additional Details</label>
                                {% if form.additional_details.errors %}
                                    <div class="invalid-feedback d-block">
                                        {{ form.additional_details.errors }}
                                    </div>
                                {% endif %}
                            </div>
                        </div>

                        <div class="col-lg-12 col-md-12 col-12 mb-3">
                            <div class="form-floating">
                                <input type="text" name="contact_information" id="id_contact_information" class="form-control" placeholder="Contact Information" value="{{ form.contact_information.value|default_if_none:'' }}">
                                <label for="id_contact_information">Contact Information</label>
                                {% if form.contact_information.errors %}
                                    <div class="invalid-feedback d-block">
                                        {{ form.contact_information.errors }}
                                    </div>
                                {% endif %}
                            </div>
                        </div>

                        <div class="col-lg-12 col-md-12 col-12 mb-3">
                            <div class="form-floating">
                                <input type="file" name="event_banner" id="id_event_banner" class="form-control" placeholder="Event Banner">
                                <label for="id_event_banner">Event Banner</label>
                                {% if form.event_banner.errors %}
                                    <div class="invalid-feedback d-block">
                                        {{ form.event_banner.errors }}
                                    </div>
                                {% endif %}
                            </div>
                        </div>

                        <div class="col-lg-4 col-12 ms-auto">
                            <button type="submit" class="form-control btn btn-primary">Add Event</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}

events/templates/events/events_list.html
{% extends 'base_layout.html' %}
{% load static %}
{% block title %} Gread - Events {% endblock %}
{% block content %}
<section class="latest-podcast-section section-padding" id="section_2" style="padding-top: 200px">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-12 col-12">
                <div class="section-title-wrap mb-5">
                    <h4 class="section-title">Upcoming Events</h4>
                </div>
            </div>
            <div class="col-lg-12 col-12 mb-4">
                <a href="{% url 'events:add_event' %}" class="btn btn-primary">Add Event</a>
                <a href="{% url 'events:my_events' %}" class="btn btn-secondary">Registered Events</a>
            </div>

            {% if events %}
                {% for event in events %}
                <div class="col-lg-10 col-12 mb-4">
                    <div class="row gy-4">
                        <div class="col-lg-3 col-12">
                            <div class="custom-block-icon-wrap">
                                <div class="custom-block-image-wrap custom-block-image-detail-page">
                                    <img src="{{ event.event_banner.url }}" class="custom-block-image img-fluid" alt="event-banner">
                                </div>
                            </div>
                        </div>

                        <div class="col-lg-9 col-12">
                            <div class="custom-block-info">
                                <div class="custom-block-top d-flex mb-1">
                                    <small class="me-4">
                                        <a href="#">
                                            <i class="bi-calendar3"></i>
                                            {{ event.datetime }}
                                        </a>
                                    </small>

                                    <small class="ms-auto">
                                        Enrollment Limit: <span class="badge">{{ event.enrollment_limit }}</span>
                                    </small>
                                </div>

                                <h2 class="mb-2">{{ event.title }}</h2>

                                <p>{{ event.description }}</p>

                                {% if event.additional_details %}
                                    <p><strong>Additional Details:</strong> {{ event.additional_details }}</p>
                                {% endif %}
                                {% if event.contact_information %}
                                    <p><strong>Contact Information:</strong> {{ event.contact_information }}</p>
                                    <p>{{ event.author.profile_picture }}</p>
                                {% endif %}

                                <div class="profile-block profile-detail-block d-flex flex-wrap align-items-center mt-5">
                                    <div class="d-flex mb-3 mb-lg-0 mb-md-0">
                                        <p>
                                            {{ event.author.username }}
                                            <img src="{% static 'images/verified.png' %}" class="verified-image img-fluid" alt="">
                                            <strong>Event Organizer</strong>
                                        </p>
                                    </div>

                                    <ul class="social-icon ms-lg-auto ms-md-auto">
                                        <li class="social-icon-item">
                                            <a href="#" class="social-icon-link bi-instagram"></a>
                                        </li>
                                        <li class="social-icon-item">
                                            <a href="#" class="social-icon-link bi-twitter"></a>
                                        </li>
                                        <li class="social-icon-item">
                                            <a href="#" class="social-icon-link bi-whatsapp"></a>
                                        </li>
                                    </ul>
                                </div>

                                <div class="enroll-btn mt-3">
                                    {% if request.user.is_authenticated and not event.is_full and request.user not in event.enrolled_users.all %}
                                        <form method="post" action="{% url 'events:enroll_event' %}">
                                            {% csrf_token %}
                                            <input type="hidden" name="event_id" value="{{ event.id }}">
                                            <button type="submit" class="btn btn-success">Enroll</button>
                                        </form>
                                    {% elif request.user in event.enrolled_users.all %}
                                        <form method="post" action="{% url 'events:unenroll_event' %}">
                                            {% csrf_token %}
                                            <input type="hidden" name="event_id" value="{{ event.id }}">
                                            <button type="submit" class="btn btn-danger">Unenroll</button>
                                        </form>
                                        <p>You are enrolled in this event.</p>
                                    {% else %}
                                        <p>Event is full.</p>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            {% else %}
                <div class="col-lg-12 col-12">
                    <div class="no-blogs-message">
                        <p>No events available.</p>
                    </div>
                </div>
            {% endif %}
        </div>
    </div>
</section>
{% endblock %}

events/templates/events/my_events.html
{#{% extends 'base_layout.html' %}#}
{##}
{#{% block content %}#}
{#<div class="container">#}
{#    <h2>My Enrolled Events</h2>#}
{#    <div class="events-list">#}
{#        {% if events %}#}
{#            {% for event in events %}#}
{#                <div class="event-card">#}
{#                    <h3>{{ event.title }}</h3>#}
{#                    <p>{{ event.shorter_description }}</p>#}
{#                    <p>Date & Time: {{ event.datetime }}</p>#}
{#                    <p>Location: {{ event.location }}</p>#}
{#                    <p>Enrollment Limit: {{ event.enrollment_limit }}</p>#}
{#                    <p>Enrolled Users: {{ event.enrolled_users.count }}</p>#}
{#                    {% if event.additional_details %}#}
{#                        <p>Additional Details: {{ event.additional_details }}</p>#}
{#                    {% endif %}#}
{#                    {% if event.contact_information %}#}
{#                        <p>Contact Information: {{ event.contact_information }}</p>#}
{#                    {% endif %}#}
{#                    <form method="post" action="{% url 'events:unenroll_event' %}">#}
{#                        {% csrf_token %}#}
{#                        <input type="hidden" name="event_id" value="{{ event.id }}">#}
{#                        <button type="submit" class="btn btn-danger">Unenroll</button>#}
{#                    </form>#}
{#                </div>#}
{#            {% endfor %}#}
{#        {% else %}#}
{#            <p>You are not enrolled in any events.</p>#}
{#        {% endif %}#}
{#    </div>#}
{#</div>#}
{#{% endblock %}#}


{% extends 'base_layout.html' %}
{% load static %}
{% block title %} Gread - My Events {% endblock %}
{% block content %}
<section class="latest-podcast-section section-padding" id="section_2" style="padding-top: 200px">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-12 col-12">
                <div class="section-title-wrap mb-5">
                    <h4 class="section-title">My Enrolled Events</h4>
                </div>
            </div>

            {% if events %}
                {% for event in events %}
                <div class="col-lg-10 col-12 mb-4">
                    <div class="row gy-4">
                        <div class="col-lg-3 col-12">
                            <div class="custom-block-icon-wrap">
                                <div class="custom-block-image-wrap custom-block-image-detail-page">
                                    <img src="{{ event.event_banner.url }}" class="custom-block-image img-fluid" alt="event-banner">
                                </div>
                            </div>
                        </div>

                        <div class="col-lg-9 col-12">
                            <div class="custom-block-info">
                                <div class="custom-block-top d-flex mb-1">
                                    <small class="me-4">
                                        <i class="bi-calendar3"></i>
                                        {{ event.datetime }}
                                    </small>

                                    <small class="ms-auto">
                                        Enrollment Limit: <span class="badge">{{ event.enrollment_limit }}</span>
                                    </small>
                                </div>

                                <h2 class="mb-2">{{ event.title }}</h2>

                                <p>{{ event.shorter_description }}</p>

                                {% if event.additional_details %}
                                    <p>Additional Details: {{ event.additional_details }}</p>
                                {% endif %}
                                {% if event.contact_information %}
                                    <p>Contact Information: {{ event.contact_information }}</p>
                                {% endif %}

                                <div class="profile-block profile-detail-block d-flex flex-wrap align-items-center mt-5">
                                    <div class="d-flex mb-3 mb-lg-0 mb-md-0">
                                        <p>
                                            {{ event.author.username }}
                                            <img src="{% static 'images/verified.png' %}" class="verified-image img-fluid" alt="">
                                            <strong>Event Organizer</strong>
                                        </p>
                                    </div>

                                    <ul class="social-icon ms-lg-auto ms-md-auto">
                                        <li class="social-icon-item">
                                            <a href="#" class="social-icon-link bi-instagram"></a>
                                        </li>
                                        <li class="social-icon-item">
                                            <a href="#" class="social-icon-link bi-twitter"></a>
                                        </li>
                                        <li class="social-icon-item">
                                            <a href="#" class="social-icon-link bi-whatsapp"></a>
                                        </li>
                                    </ul>
                                </div>

                                <div class="enroll-btn mt-3">
                                    <form method="post" action="{% url 'events:unenroll_event' %}">
                                        {% csrf_token %}
                                        <input type="hidden" name="event_id" value="{{ event.id }}">
                                        <button type="submit" class="btn btn-danger">Unenroll</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            {% else %}
                <div class="col-lg-12 col-12">
                    <div class="no-blogs-message">
                        <p>You are not enrolled in any events.</p>
                    </div>
                </div>
            {% endif %}
        </div>
    </div>
</section>
{% endblock %}