accounts/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views


app_name = 'accounts'

urlpatterns = [
    path('profile/<str:username>/', views.profile_view, name='profile'),
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    # path('password_reset/', name='password_reset'),
    # Password reset views
    path('password_reset/',
         auth_views.PasswordResetView.as_view(template_name='accounts/password_reset_form.html'),
         name='password_reset'),
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),
         name='password_reset_done'),
    # path('password-reset-confirm/<uidb64>/<token>/',
    #      auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html'),
    #      name='password_reset_confirm'),
    # path('password-reset-complete/',
    #      auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),
    #      name='password_reset_complete'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),
         name='password_reset_complete.html'),
    path('clear_cookie_consent_session/', views.clear_cookie_consent_session, name='clear_cookie_consent_session'),
    # path('', include('django.contrib.auth.urls')),
]

blogs/urls.py
"""
URLS - FOR Blogs App
Urls - call the functions in views.py. Views functions contain logic regd. what to send as response.

"""

from django.urls import path
from . import views  # importing views.py from current directory(hence used '.')

app_name = 'blogs'

urlpatterns = [
    path('', views.blogs_list, name='blogs_list'),
    path('create/', views.blog_create, name='blog_create'),
    path('drafts/', views.drafts_list, name='drafts_list'),
    path('load_draft/', views.load_draft, name='load_draft'),

    path('recently_viewed/', views.recently_viewed_blogs, name='recently_viewed_blogs'),
    # below regex: slug can be any character(word, number etc), also includes'-' and length is nolimit.
    path('<slug:slug>/', views.blog_detail, name='blog_detail'),
    path('<slug:slug>/like/', views.like_post, name='like_post'),

]

gread/urls.py
"""
URLS - FOR Base App - Gread.com
Urls - call the functions in views.py. Views functions contain logic regd. what to send as response.

"""

from django.contrib import admin
from django.urls import path, include  # here include is used to include other urls (from apps)
from . import views  # importing views.py from current directory(hence used '.')
from blogs import views as blogs_views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns  #for loading static files
from django.conf.urls.static import static  #For media Files
from django.conf import settings  #importing all vars and functions from settins.py file
from accounts.admin_site import custom_admin_site

urlpatterns = [
    path('', views.homepage, name='home'),
    # path('', blogs_views.blogs_list, name='home'),
    path('admin/', admin.site.urls),
    # path('admin/', custom_admin_site.urls),
    path('about/', views.about, name='about'),

    # We need to register urls for other apps here in the base urls.py, in order to access them
    path('blogs/', include('blogs.urls')),
    path('accounts/', include('accounts.urls')),
    path("accounts/", include("django.contrib.auth.urls")),
    path('events/', include('events.urls')),

    #     Test Urls
    path('index/', views.index, name='index'),
    path('contact/', views.contact, name='contact'),

]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.apps import apps
from django.contrib.auth.models import User


class Member(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    bio = models.TextField(blank=True)
    profile_picture = models.ImageField(default='default.png', blank=True, null=True)
    city = models.CharField(max_length=100, blank=True, null=True)
    province = models.CharField(max_length=100, blank=True, null=True)

    def __str__(self):
        return self.user.username

    @property
    def number_of_blogs_posted(self):
        Blog = apps.get_model('blogs', 'Blog')
        return Blog.objects.filter(author=self.user, status='published').count()

accounts/forms.py
# forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Member


class CustomUserCreationForm(UserCreationForm):
    bio = forms.CharField(required=False, widget=forms.Textarea)
    profile_picture = forms.ImageField(required=False)
    city = forms.CharField(required=False)
    province = forms.CharField(required=False)

    class Meta:
        model = User
        fields = (
            'username', 'password1', 'password2', 'email', 'first_name', 'last_name', 'bio', 'profile_picture', 'city',
            'province')

    def save(self, commit=True):
        user = super().save(commit=False)
        if commit:
            user.save()
        else:
            user.save()  # Ensure the User is saved before proceeding

        # Ensure the related Member instance exists
        Member.objects.get_or_create(user=user)

        # Access and update the Member instance via user.member
        user.member.bio = self.cleaned_data.get('bio', '')
        user.member.profile_picture = self.cleaned_data.get('profile_picture', None)
        user.member.city = self.cleaned_data.get('city', '')
        user.member.province = self.cleaned_data.get('province', '')

        user.member.save()

        return user

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
from django.contrib import messages
from django.http import JsonResponse
from accounts.models import Member
from .forms import CustomUserCreationForm
from django.contrib.auth.models import User

# Signup - View
def signup_view(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save()
            login(request, user)
            request.session['cookie_consent_needed'] = True
            messages.info(request, "Welcome! Please review and accept our cookie policy.")
            return redirect('home')
    else:
        form = CustomUserCreationForm()
    return render(request, 'accounts/signup.html', {'form': form})


# Login - View
def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)

            # Skip Member check for superuser
            if user.is_superuser:
                if not request.session.get('cookie_consent_given'):
                    request.session['cookie_consent_needed'] = True  # Set session variable
                return redirect('admin:index')

            # Ensure the user has a Member instance
            if not hasattr(user, 'member'):
                Member.objects.create(user=user)

            if not request.session.get('cookie_consent_given'):
                request.session['cookie_consent_needed'] = True  # Set session variable

            cookie_consent = request.COOKIES.get(f'cookie_consent_{user.id}', None)
            if cookie_consent == 'accepted':
                if 'next' in request.POST:
                    return redirect(request.POST.get('next'))
                else:
                    return redirect('home')
            else:
                request.session['cookie_consent_needed'] = True
                return redirect('home')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'form': form})


def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('blogs:blogs_list')


# Reste View - back to blogs
def reset_view(request):
    return redirect('blogs:')


def clear_cookie_consent_session(request):
    if request.method == 'POST':
        if 'cookie_consent_needed' in request.session:
            del request.session['cookie_consent_needed']
            return JsonResponse({'message': 'Session variable cleared successfully'})
        else:
            return JsonResponse({'message': 'Session variable not found'}, status=404)
    else:
        return JsonResponse({'message': 'Method not allowed'}, status=405)


# Profile Page - View
def profile_view(request, username):
    user = get_object_or_404(User, username=username)
    member = get_object_or_404(Member, user=user)

    context = {
        'member': member,
        'is_own_profile': request.user == user
    }

    if request.user.is_authenticated and request.user == user:
        cookie_consent = request.COOKIES.get(f'cookie_consent_{user.id}')
        if cookie_consent == 'accepted':
            user_id = user.id
            visits_cookie_name = f'visits_{user_id}'
            visits = int(request.COOKIES.get(visits_cookie_name, '0'))
            context['visits'] = visits
        else:
            context['visits'] = None
    else:
        context['visits'] = None

    return render(request, 'accounts/profile.html', context)

accounts/templates/accounts/login.html
{#{% extends 'base_layout.html' %}#}
{##}
{#{% block content %}#}
{#    <h1>Login</h1>#}
{#    <form class="site-form" action="{% url 'accounts:login' %}" method="post">#}
{#    {% csrf_token %}#}
{#        {{ form }}#}
{#    <!-- For Redirection -->#}
{#        {% if request.GET.next %}#}
{#            <input type="hidden" name="next" value="{{ request.GET.next }}">#}
{#        {% endif %}#}
{#    <input type="submit" name="" value="Login">#}
{#    <button type="button" class="btn btn-link" onclick="redirectToPasswordReset()">Forgot Password?</button>#}
{#    </form>#}
{#    <script>#}
{#        function redirectToPasswordReset() {#}
{#            window.location.href = "{% url 'accounts:password_reset' %}";#}
{#        }#}
{#    </script>#}
{#{% endblock %}#}


{% extends 'base_layout.html' %}

{% block content %}
<section class="contact-section section-padding" style="padding-top: 200px">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-12 mx-auto">
                <div class="section-title-wrap mb-5">
                    <h4 class="section-title">Login</h4>
                </div>

                <form action="{% url 'accounts:login' %}" method="post" class="custom-form contact-form" role="form">
                    {% csrf_token %}
                    {% if form.non_field_errors %}
                        <div>
                            {{ form.non_field_errors }}
                        </div>
                    {% endif %}
                    <div class="row">
                        <div class="col-lg-12 col-md-12 col-12 mb-3">
                            <div class="form-floating">
                                <input type="text" name="username" id="id_username" class="form-control" placeholder="Username" value="{{ form.username.value|default_if_none:'' }}">
                                <label for="id_username">Username</label>
                                {% if form.username.errors %}
                                    <div class="invalid-feedback d-block">
                                        {{ form.username.errors }}
                                    </div>
                                {% endif %}
                            </div>
                        </div>

                        <div class="col-lg-12 col-md-12 col-12 mb-3">
                            <div class="form-floating">
                                <input type="password" name="password" id="id_password" class="form-control" placeholder="Password" value="{{ form.password.value|default_if_none:'' }}">
                                <label for="id_password">Password</label>
                                {% if form.password.errors %}
                                    <div class="invalid-feedback d-block">
                                        {{ form.password.errors }}
                                    </div>
                                {% endif %}
                            </div>
                        </div>

                        {% if request.GET.next %}
                            <input type="hidden" name="next" value="{{ request.GET.next }}">
                        {% endif %}

                        <div class="col-lg-4 col-12 ms-auto">
                            <button type="submit" class="form-control btn btn-primary">Login</button>
                        </div>

                        <div class="col-lg-4 col-12 ms-auto">
                            <button type="button" class="form-control btn btn-link" onclick="redirectToPasswordReset()">Forgot Password?</button>
                        </div>
                    </div>
                </form>
                <script>
                    function redirectToPasswordReset() {
                        window.location.href = "{% url 'accounts:password_reset' %}";
                    }
                </script>
            </div>
        </div>
    </div>
</section>
{% endblock %}

accounts/templates/accounts/password_reset_complete.html
{#{% extends 'base_layout.html' %}#}
{#{% block content %}#}
{#    <div class="container my-3 p-3">#}
{#        <div class="row justify-content-center">#}
{#            <div class="col-lg-5">#}
{#                <div class="card shadow-lg border-0 rounded-lg mt-0 mb-3">#}
{#                    <div class="alert alert-info">#}
{#                        Your password has been set. You may go ahead and <a href="{% url 'login' %}">Login Here</a>#}
{#                    </div>#}
{#                </div>#}
{#            </div>#}
{#        </div>#}
{#    </div>#}
{#{% endblock content %}#}

{% extends 'base_layout.html' %}

{% block title %}Password Set{% endblock %}

{% block content %}
<section class="contact-section section-padding" style="padding-top: 200px">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-12 mx-auto">
                <div class="section-title-wrap mb-5">
                    <h4 class="section-title">Password Set</h4>
                </div>

                <div class="alert alert-info">
                    Your password has been set. You may go ahead and <a href="{% url 'login' %}">Login Here</a>.
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

accounts/templates/accounts/password_reset_confirm.html
{#{% extends 'base_layout.html' %}#}
{#{% block title %} Password Reset {% endblock title%}#}
{#{% block content %}#}
{#    <div class="form-content my-3 p-3">#}
{#        <div class="container">#}
{#            <div class="row justify-content-center">#}
{#                <div class="col-lg-5">#}
{#                    {% if validlink %}#}
{#                        <div class="card shadow-lg border-0 rounded-lg mt-0 mb-3">#}
{#                            <div class="card-header justify-content-center">#}
{#                              <h3 class="font-weight-light my-4 text-center">Reset Your Password</h3>#}
{#                            </div>#}
{#                            {% if form.errors %}#}
{#                                <div class="alert alert-danger alert-dismissible" role="alert">#}
{#                                    <div id="form_errors">#}
{#                                        {% for key, value in form.errors.items %}#}
{#                                            <strong>{{ value }}</strong>#}
{#                                        {% endfor %}#}
{#                                    </div>#}
{#                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">#}
{#                                        <span aria-hidden="true">&times;</span>#}
{#                                    </button>#}
{#                                </div>#}
{#                            {% endif %}#}
{##}
{#                            <div class="card-body">#}
{#                                <form method="POST">#}
{#                                    {% csrf_token %}#}
{#                                    <div class="form-row">#}
{#                                        <div class="col-md-10 offset-md-1">#}
{#                                            <div class="form-group">#}
{#                                                <label class="small mb-1" for="id_new_password1">New Password</label>#}
{#                                                <input type="password" name="new_password1" autocomplete="new-password"#}
{#                                                       class="form-control" required id="id_new_password1"#}
{#                                                       placeholder="Enter password"/>#}
{#                                                <span>#}
{#                                                </span>#}
{#                                            </div>#}
{#                                        </div>#}
{#                                    </div>#}
{#                                    <div class="form-row">#}
{#                                        <div class="col-md-10 offset-md-1">#}
{#                                            <div class="form-group">#}
{#                                                <label class="small mb-1" for="id_new_password2">New Password Confirmation</label>#}
{#                                                <input type="password" name="new_password2" autocomplete="new-password"#}
{#                                                       required id="id_new_password2" class="form-control"#}
{#                                                       placeholder="Confirm password"/>#}
{#                                            </div>#}
{#                                        </div>#}
{#                                    </div>#}
{#                                    <div class="form-row">#}
{#                                        <div class="col-md-10 offset-md-1">#}
{#                                            <div class="form-group mt-0 mb-1">#}
{#                                                <button type="submit" class="col-md-12 btn btn-dark" id="reset">Reset Password</button>#}
{#                                            </div>#}
{#                                        </div>#}
{#                                    </div>#}
{#                                </form>#}
{#                            </div>#}
{#                        </div>#}
{#                    {% else %}#}
{#                    <div class="alert alert-warning">#}
{#                        The password reset link was invalid, possibly because it has already been used.#}
{#                        Please request a new password reset.#}
{#                    </div>#}
{#                    {% endif %}#}
{#                </div>#}
{#            </div>#}
{#        </div>#}
{#    </div>#}
{#{% endblock content %}#}
{##}
{#{% extends "base_layout.html" %}#}
{##}
{#{% block title %}Enter new password{% endblock %}#}
{##}
{#{% block content %}#}
{##}
{#{% if validlink %}#}
{##}
{#<h1>Set a new password!</h1>#}
{#<form method="POST">#}
{#  {% csrf_token %}#}
{#  {{ form.as_p }}#}
{#  <input type="submit" value="Change my password">#}
{#</form>#}
{##}
{#{% else %}#}
{##}
{#<p>The password reset link was invalid, possibly because it has already been used. Please request a new password reset.#}
{#</p>#}
{##}
{#{% endif %}#}
{#{% endblock %}#}

{% extends 'base_layout.html' %}

{% block title %}Enter new password{% endblock %}

{% block content %}
<section class="contact-section section-padding" style="padding-top: 200px">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-12 mx-auto">
                <div class="section-title-wrap mb-5">
                    <h4 class="section-title">Set a new password!</h4>
                </div>

                {% if validlink %}
                <form method="POST" class="custom-form contact-form" role="form">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-lg-12 col-md-12 col-12 mb-3">
                            <div class="form-floating">
                                <input type="password" name="new_password1" id="id_new_password1" class="form-control" placeholder="New Password" required>
                                <label for="id_new_password1">New Password</label>
                                {% if form.new_password1.errors %}
                                    <div class="invalid-feedback d-block">
                                        {{ form.new_password1.errors }}
                                    </div>
                                {% endif %}
                            </div>
                        </div>

                        <div class="col-lg-12 col-md-12 col-12 mb-3">
                            <div class="form-floating">
                                <input type="password" name="new_password2" id="id_new_password2" class="form-control" placeholder="New Password Confirmation" required>
                                <label for="id_new_password2">New Password Confirmation</label>
                                {% if form.new_password2.errors %}
                                    <div class="invalid-feedback d-block">
                                        {{ form.new_password2.errors }}
                                    </div>
                                {% endif %}
                            </div>
                        </div>

                        <div class="col-lg-4 col-12 ms-auto">
                            <button type="submit" class="form-control btn btn-primary">Change my password</button>
                        </div>
                    </div>
                </form>
                {% else %}
                <div class="alert alert-warning mt-5">
                    The password reset link was invalid, possibly because it has already been used. Please request a new password reset.
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</section>
{% endblock %}

accounts/templates/accounts/signup.html
{#{% extends 'base_layout.html' %}#}
{##}
{#{% block content %}#}
{#    <h1>SignUp</h1>#}
{#    <form class="site-form" action="/accounts/signup/" method="post" enctype="multipart/form-data">#}
{#    {% csrf_token %}#}
{#        {{ form.as_p }}#}
{#    <input type="submit" name="" value="Signup">#}
{#    </form>#}
{#{% endblock %}#}

{% extends 'base_layout.html' %}

{% block content %}
<section class="contact-section section-padding" style="padding-top: 200px">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-12 mx-auto">
                <div class="section-title-wrap mb-5">
                    <h4 class="section-title">Sign Up</h4>
                </div>

                <form action="{% url 'accounts:signup' %}" method="post" class="custom-form contact-form" enctype="multipart/form-data" role="form">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-lg-12 col-md-12 col-12 mb-3">
                            <div class="form-floating">
                                <input type="text" name="username" id="id_username" class="form-control" placeholder="Username" value="{{ form.username.value|default_if_none:'' }}">
                                <label for="id_username">Username</label>
                                {% if form.username.errors %}
                                    <div class="invalid-feedback d-block">
                                        {{ form.username.errors }}
                                    </div>
                                {% endif %}
                            </div>
                        </div>

                        <div class="col-lg-12 col-md-12 col-12 mb-3">
                            <div class="form-floating">
                                <input type="password" name="password1" id="id_password1" class="form-control" placeholder="Password">
                                <label for="id_password1">Password</label>
                                {% if form.password1.errors %}
                                    <div class="invalid-feedback d-block">
                                        {{ form.password1.errors }}
                                    </div>
                                {% endif %}
                            </div>
                        </div>

                        <div class="col-lg-12 col-md-12 col-12 mb-3">
                            <div class="form-floating">
                                <input type="password" name="password2" id="id_password2" class="form-control" placeholder="Password confirmation">
                                <label for="id_password2">Password confirmation</label>
                                {% if form.password2.errors %}
                                    <div class="invalid-feedback d-block">
                                        {{ form.password2.errors }}
                                    </div>
                                {% endif %}
                            </div>
                        </div>

                        <div class="col-lg-12 col-md-12 col-12 mb-3">
                            <div class="form-floating">
                                <input type="email" name="email" id="id_email" class="form-control" placeholder="Email address" value="{{ form.email.value|default_if_none:'' }}">
                                <label for="id_email">Email address</label>
                                {% if form.email.errors %}
                                    <div class="invalid-feedback d-block">
                                        {{ form.email.errors }}
                                    </div>
                                {% endif %}
                            </div>
                        </div>

                        <div class="col-lg-6 col-md-6 col-12 mb-3">
                            <div class="form-floating">
                                <input type="text" name="first_name" id="id_first_name" class="form-control" placeholder="First name" value="{{ form.first_name.value|default_if_none:'' }}">
                                <label for="id_first_name">First name</label>
                                {% if form.first_name.errors %}
                                    <div class="invalid-feedback d-block">
                                        {{ form.first_name.errors }}
                                    </div>
                                {% endif %}
                            </div>
                        </div>

                        <div class="col-lg-6 col-md-6 col-12 mb-3">
                            <div class="form-floating">
                                <input type="text" name="last_name" id="id_last_name" class="form-control" placeholder="Last name" value="{{ form.last_name.value|default_if_none:'' }}">
                                <label for="id_last_name">Last name</label>
                                {% if form.last_name.errors %}
                                    <div class="invalid-feedback d-block">
                                        {{ form.last_name.errors }}
                                    </div>
                                {% endif %}
                            </div>
                        </div>

                        <div class="col-lg-12 col-md-12 col-12 mb-3">
                            <div class="form-floating">
                                <textarea name="bio" id="id_bio" class="form-control" placeholder="Bio">{{ form.bio.value|default_if_none:'' }}</textarea>
                                <label for="id_bio">Bio</label>
                                {% if form.bio.errors %}
                                    <div class="invalid-feedback d-block">
                                        {{ form.bio.errors }}
                                    </div>
                                {% endif %}
                            </div>
                        </div>

                        <div class="col-lg-12 col-md-12 col-12 mb-3">
                            <div class="form-floating">
                                <input type="file" name="profile_picture" id="id_profile_picture" class="form-control" placeholder="Profile picture">
                                <label for="id_profile_picture">Profile picture</label>
                                {% if form.profile_picture.errors %}
                                    <div class="invalid-feedback d-block">
                                        {{ form.profile_picture.errors }}
                                    </div>
                                {% endif %}
                            </div>
                        </div>

                        <div class="col-lg-6 col-md-6 col-12 mb-3">
                            <div class="form-floating">
                                <input type="text" name="city" id="id_city" class="form-control" placeholder="City" value="{{ form.city.value|default_if_none:'' }}">
                                <label for="id_city">City</label>
                                {% if form.city.errors %}
                                    <div class="invalid-feedback d-block">
                                        {{ form.city.errors }}
                                    </div>
                                {% endif %}
                            </div>
                        </div>

                        <div class="col-lg-6 col-md-6 col-12 mb-3">
                            <div class="form-floating">
                                <input type="text" name="province" id="id_province" class="form-control" placeholder="Province" value="{{ form.province.value|default_if_none:'' }}">
                                <label for="id_province">Province</label>
                                {% if form.province.errors %}
                                    <div class="invalid-feedback d-block">
                                        {{ form.province.errors }}
                                    </div>
                                {% endif %}
                            </div>
                        </div>

                        <div class="col-lg-4 col-12 ms-auto">
                            <button type="submit" class="form-control btn btn-primary">Signup</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}