accounts/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views


app_name = 'accounts'

urlpatterns = [
    path('profile/<str:username>/', views.profile_view, name='profile'),
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    # path('password_reset/', name='password_reset'),
    # Password reset views
    path('password_reset/',
         auth_views.PasswordResetView.as_view(template_name='accounts/password_reset_form.html'),
         name='password_reset'),
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),
         name='password_reset_done'),
    # path('password-reset-confirm/<uidb64>/<token>/',
    #      auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html'),
    #      name='password_reset_confirm'),
    # path('password-reset-complete/',
    #      auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),
    #      name='password_reset_complete'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),
         name='password_reset_complete.html'),
    path('clear_cookie_consent_session/', views.clear_cookie_consent_session, name='clear_cookie_consent_session'),
    # path('', include('django.contrib.auth.urls')),
]

blogs/urls.py
"""
URLS - FOR Blogs App
Urls - call the functions in views.py. Views functions contain logic regd. what to send as response.

"""

from django.urls import path
from . import views  # importing views.py from current directory(hence used '.')

app_name = 'blogs'

urlpatterns = [
    path('', views.blogs_list, name='blogs_list'),
    path('create/', views.blog_create, name='blog_create'),
    path('drafts/', views.drafts_list, name='drafts_list'),
    path('load_draft/', views.load_draft, name='load_draft'),

    path('recently_viewed/', views.recently_viewed_blogs, name='recently_viewed_blogs'),
    # below regex: slug can be any character(word, number etc), also includes'-' and length is nolimit.
    path('<slug:slug>/', views.blog_detail, name='blog_detail'),
    path('<slug:slug>/like/', views.like_post, name='like_post'),

]

gread/urls.py
"""
URLS - FOR Base App - Gread.com
Urls - call the functions in views.py. Views functions contain logic regd. what to send as response.

"""

from django.contrib import admin
from django.urls import path, include  # here include is used to include other urls (from apps)
from . import views  # importing views.py from current directory(hence used '.')
from blogs import views as blogs_views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns  #for loading static files
from django.conf.urls.static import static  #For media Files
from django.conf import settings  #importing all vars and functions from settins.py file
from accounts.admin_site import custom_admin_site

urlpatterns = [
    path('', views.homepage, name='home'),
    # path('', blogs_views.blogs_list, name='home'),
    path('admin/', admin.site.urls),
    # path('admin/', custom_admin_site.urls),
    path('about/', views.about, name='about'),

    # We need to register urls for other apps here in the base urls.py, in order to access them
    path('blogs/', include('blogs.urls')),
    path('accounts/', include('accounts.urls')),
    path("accounts/", include("django.contrib.auth.urls")),
    path('events/', include('events.urls')),

    #     Test Urls
    path('index/', views.index, name='index'),
    path('contact/', views.contact, name='contact'),

]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogs/models.py
"""
1. We do migration so that this class/model (which is an instance of the database table),
is mapped to a db table. -- basically django doesnt know that this class = some table
2. CREATE a Migration file - tracks any changes that we make in any model. -- by running makemigrations
3. ORM bridges gap between code and the database. We can do things like save instance of model,
retrieve model from db etc.

"""

from django.db import models
from django.contrib.auth.models import User
from accounts.models import Member


class Blog(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)  # automatically populate date with this bool value
    thumbnail = models.ImageField(default='default.png', blank=True)
    author = models.ForeignKey(User, default=None, on_delete=models.CASCADE)
    status = models.CharField(max_length=10, choices=[('draft', 'Draft'), ('published', 'Published')],
                              default='published')

    def __str__(self):
        return self.title

    def shorter_body(self):
        return self.body[:70] + "..."


# Model for Comments on Blogs
class Comment(models.Model):
    post = models.ForeignKey(Blog, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    body = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    """
    Note: ForeignKey establishes a one-to-many relationship.
    Hence a single comment can have many replies, but each reply is related to exactly one parent comment.
    """
    parent = models.ForeignKey('self', null=True, blank=True, related_name='replies', on_delete=models.CASCADE)

    def __str__(self):
        return f"Comment by {self.author} on {self.post}"

    @property
    def is_reply(self):
        return self.parent is not None


# Model for Likes on Blogs
class Like(models.Model):
    post = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name='likes')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('post', 'user')

    def __str__(self):
        return f"{self.user} likes {self.post}"

blogs/forms.py
from django import forms
from . import models
from django.utils.text import slugify
from .models import Blog, Comment


class CreateBlog(forms.ModelForm):
    class Meta:
        model = models.Blog
        fields = ['title', 'body', 'slug', 'thumbnail']

    def clean_title(self):
        title = self.cleaned_data.get('title')
        slug = slugify(title)
        if Blog.objects.filter(slug=slug).exists():
            raise forms.ValidationError(
                "A blog post with a similar title already exists. Please try a different title.")
        return title


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['body']
        widgets = {
            'body': forms.Textarea(attrs={'rows': 4}),
        }

blogs/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Blog, Member, Comment, Like
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from . import forms
from django.db.models import Q, Count
from django.contrib import messages
from .forms import CreateBlog, CommentForm


def blogs_list(request):
    query = request.GET.get("q", "")
    field = request.GET.get("field", "")

    if query and field:
        if field == "title":
            blogs = Blog.objects.filter(Q(title__icontains=query)).order_by('pub_date')
        elif field == "body":
            blogs = Blog.objects.filter(Q(body__icontains=query)).order_by('pub_date')
        elif field == "author":
            blogs = Blog.objects.filter(Q(author__username__icontains=query)).order_by('pub_date')
        else:  # No filter case or empty string case
            blogs = Blog.objects.filter(
                Q(title__icontains=query) |
                Q(body__icontains=query) |
                Q(author__username__icontains=query)
            ).order_by('pub_date')
    else:
        blogs = Blog.objects.all().order_by('pub_date')

    # Annotate each blog with the count of likes
    blogs = blogs.annotate(likes_count=Count('likes'))

    return render(request, 'blogs/blogs_list.html', {'blog_details': blogs, 'query': query, 'field': field})


def blog_detail(request, slug):
    blog = get_object_or_404(Blog, slug=slug)
    comments = Comment.objects.filter(post=blog, parent=None).order_by('-created_at')
    user_likes_post = Like.objects.filter(post=blog,
                                          user=request.user).exists() if request.user.is_authenticated else False

    # Handle recently viewed blogs
    recently_viewed = request.session.get('recently_viewed', [])
    if slug in recently_viewed:
        recently_viewed.remove(slug)
    recently_viewed.insert(0, slug)
    if len(recently_viewed) > 5:
        recently_viewed.pop()
    request.session['recently_viewed'] = recently_viewed

    # Initialize forms
    form = CommentForm()
    blog_form = CreateBlog(instance=blog) if request.user == blog.author else None

    # If user sends a POST call from this UI (Comments add)
    if request.method == 'POST':
        form_type = request.POST.get('form_type')

        if form_type == 'comment_form':
            if not request.user.is_authenticated:
                return redirect('accounts:login')
            form = CommentForm(request.POST)
            if form.is_valid():
                comment = form.save(commit=False)
                comment.post = blog
                comment.author = request.user
                parent_id = request.POST.get('parent_id')
                if parent_id:
                    parent_comment = get_object_or_404(Comment, id=parent_id)
                    comment.parent = parent_comment
                comment.save()
                return redirect('blogs:blog_detail', slug=blog.slug)

        elif form_type == 'blog_form' and request.user == blog.author:
            blog_form = CreateBlog(request.POST, request.FILES, instance=blog)
            if blog_form.is_valid():
                blog_form.save()
                return redirect('blogs:blog_detail', slug=blog.slug)

    context = {
        'blog': blog,
        'comments': comments,
        'form': form,
        'blog_form': blog_form,
        'user_likes_post': user_likes_post,
        'recently_viewed': recently_viewed
    }
    return render(request, 'blogs/blog_detail.html', context)


@login_required(login_url="/accounts/login/")  # Redirect if user not logged-in
def blog_create(request):
    draft_key = 'blog_draft'
    if request.method == 'POST':
        form = CreateBlog(request.POST, request.FILES)
        if form.is_valid():
            if 'publish' in request.POST:
                # Save the blog to the database
                blog = form.save(commit=False)
                blog.author = request.user  # Set the author to the currently logged-in user
                blog.status = 'published'
                blog.save()
                # Clear the draft from session
                if draft_key in request.session:
                    del request.session[draft_key]
                return redirect('blogs:blogs_list')
            elif 'save_draft' in request.POST:
                # Save the draft in session
                draft_data = {
                    'title': form.cleaned_data['title'],
                    'body': form.cleaned_data['body'],
                }
                # Handle the thumbnail field correctly
                thumbnail = form.cleaned_data['thumbnail']
                if thumbnail:
                    if hasattr(thumbnail, 'name'):
                        draft_data['thumbnail'] = thumbnail.name
                    else:
                        draft_data['thumbnail'] = thumbnail
                else:
                    draft_data['thumbnail'] = None

                request.session[draft_key] = draft_data
                return redirect('blogs:drafts_list')
    else:
        form = CreateBlog()
    return render(request, 'blogs/blog_create.html', {'form': form})


@login_required(login_url="/accounts/login/")  # Redirect to login page if not logged in
def recently_viewed_blogs(request):
    recently_viewed = request.session.get('recently_viewed', [])
    valid_blogs = []
    valid_slugs = []

    for slug in recently_viewed:
        try:
            blog = Blog.objects.get(slug=slug)
            valid_blogs.append(blog)
            valid_slugs.append(slug)
        except Blog.DoesNotExist:
            continue

    # Update session with only valid slugs
    request.session['recently_viewed'] = valid_slugs

    return render(request, 'blogs/recently_viewed.html', {'blogs': valid_blogs})


@login_required(login_url="/accounts/login/")  # Redirect if user not logged-in
def drafts_list(request):
    session_draft = request.session.get('blog_draft', None)
    # user_drafts = Blog.objects.filter(author=request.user, status='draft')

    return render(request, 'blogs/drafts_list.html', {
        'session_draft': session_draft,
        # 'user_drafts': user_drafts,
    })


@login_required(login_url="/accounts/login/")  # Redirect if user not logged-in
def load_draft(request):
    draft_data = request.session.get('blog_draft')

    if draft_data:
        form = CreateBlog(initial={
            'title': draft_data.get('title'),
            'body': draft_data.get('body'),
            'thumbnail': draft_data.get('thumbnail'),
        })
        return render(request, 'blogs/blog_create.html', {'form': form})
    else:
        return redirect('blogs:drafts_list')


@login_required
def like_post(request, slug):
    post = get_object_or_404(Blog, slug=slug)
    like, created = Like.objects.get_or_create(post=post, user=request.user)
    if not created:
        like.delete()
    return redirect('blogs:blog_detail', slug=slug)

blogs/templates/blogs/blog_create.html
{% extends 'base_layout.html' %}
{% load static %}
{% block title %} Gread - Create Blog {% endblock %}
{% block content %}
<section class="contact-section section-padding" style="padding-top: 200px">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-12 mx-auto">
                <div class="section-title-wrap mb-5">
                    <h4 class="section-title">{% if form.initial.title %}Edit Your Draft{% else %}Create a New Blog{% endif %}</h4>
                </div>

                <form action="{% url 'blogs:blog_create' %}" method="post" class="custom-form contact-form" enctype="multipart/form-data" role="form">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-lg-12 col-md-12 col-12 mb-3">
                            <div class="form-floating">
                                <input type="text" name="title" id="id_title" class="form-control" placeholder="Title" value="{{ form.title.value|default_if_none:'' }}">
                                <label for="id_title">Title</label>
                                {% if form.title.errors %}
                                    <div class="invalid-feedback d-block">
                                        {{ form.title.errors }}
                                    </div>
                                {% endif %}
                            </div>
                        </div>

                        <div class="col-lg-12 col-md-12 col-12 mb-3">
                            <div class="form-floating">
                                <input type="text" name="slug" id="id_slug" class="form-control" placeholder="Slug" value="{{ form.slug.value|default_if_none:'' }}">
                                <label for="id_slug">Slug</label>
                                {% if form.slug.errors %}
                                    <div class="invalid-feedback d-block">
                                        {{ form.slug.errors }}
                                    </div>
                                {% endif %}
                            </div>
                        </div>

                        <div class="col-lg-12 col-md-12 col-12 mb-3">
                            <div class="form-floating">
                                <textarea name="body" id="id_body" class="form-control" placeholder="Body">{{ form.body.value|default_if_none:'' }}</textarea>
                                <label for="id_body">Body</label>
                                {% if form.body.errors %}
                                    <div class="invalid-feedback d-block">
                                        {{ form.body.errors }}
                                    </div>
                                {% endif %}
                            </div>
                        </div>

                        <div class="col-lg-12 col-md-12 col-12 mb-3">
                            <div class="form-floating">
                                <input type="file" name="thumbnail" id="id_thumbnail" class="form-control" placeholder="Thumbnail">
                                <label for="id_thumbnail">Thumbnail</label>
                                {% if form.thumbnail.errors %}
                                    <div class="invalid-feedback d-block">
                                        {{ form.thumbnail.errors }}
                                    </div>
                                {% endif %}
                            </div>
                        </div>

                        <div class="col-lg-4 col-12 ms-auto">
                            <button type="submit" name="publish" class="form-control btn btn-primary">Publish</button>
                        </div>

                        <div class="col-lg-4 col-12 ms-auto">
                            <button type="submit" name="save_draft" class="form-control btn btn-secondary">Save Draft</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>
<script src="/static/slugify.js"></script>
{% endblock %}

blogs/templates/blogs/blog_detail.html
{% extends 'base_layout.html' %}

{% block content %}
<style>
    .reply-form {
        display: none;
        margin-left: 20px;
    }
    .reply {
        margin-left: 20px;
    }
    .comments {
    max-width: 100%;
}

.comment {
    position: relative;
}

.replies {
    position: relative;
    border-left: 2px solid #e0e0e0;
    padding-left: 15px;
    margin-left: 15px;
}

.replies:before {
    content: "";
    position: absolute;
    left: -15px;
    top: 0;
    bottom: 0;
    width: 15px;
    border-top: 2px solid #e0e0e0;
    border-left: 2px solid #e0e0e0;
    height: 100%;
}

.card {
    margin-bottom: 10px;
}

.card-body {
    padding: 10px;
}
.card {
    max-width: 600px; /* Set a maximum width for the card */
}

.reply-form {
    margin-top: 10px;
}

.btn-link {
    padding: 0;
}

.reply-card {
    position: relative;
}

.reply-card:before {
    content: "";
    position: absolute;
    left: -15px;
    top: 10px; /* Align with the top padding of the card */
    width: 15px;
    border-top: 2px solid #e0e0e0;
}

</style>

<script>
    function toggleReplyForm(commentId) {
        var replyForm = document.getElementById('reply-form-' + commentId);
        if (replyForm.style.display === 'none' || replyForm.style.display === '') {
            replyForm.style.display = 'block';
        } else {
            replyForm.style.display = 'none';
        }
    }
</script>

<div class="blog-detail">
<!-- Blog Details -->
<section class="blog-detail-section section-padding" id="section_blog_detail" style="padding-top: 200px">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-12 col-12">
                <div class="section-title-wrap mb-5">
                    <h4 class="section-title">{{ blog.title }}</h4>
                </div>
            </div>

            <div class="col-lg-12 col-12 mb-4">
                <div class="row gy-4">
                    <div class="col-lg-3 col-12">
                        <div class="custom-block-icon-wrap">
                            <div class="custom-block-image-wrap custom-block-image-detail-page">
                                <img src="{{ blog.thumbnail.url }}" class="custom-block-image img-fluid" alt="Blog thumbnail">
                            </div>
                        </div>
                    </div>

                    <div class="col-lg-9 col-12">
                        <div class="custom-block-info">
                            <div class="custom-block-top d-flex mb-1">
                                <small class="me-4">
                                    <i class="bi-calendar3"></i>
                                    {{ blog.pub_date }}
                                </small>
                            </div>

                            <p>{{ blog.body }}</p>

                            {% if user.is_authenticated %}
                                <form action="{% url 'blogs:like_post' blog.slug %}" method="post" style="display: inline;">
                                    {% csrf_token %}
                                    <button type="submit" class="btn {% if user_likes_post %}btn-danger{% else %}btn-primary{% endif %}">
                                        {% if user_likes_post %}
                                            <i class="bi bi-hand-thumbs-down"></i>
                                        {% else %}
                                            <i class="bi bi-hand-thumbs-up"></i>
                                        {% endif %}
                                    </button>
                                </form>
                            {% endif %}

                            {% if request.user == blog.author %}
                                <div class="edit-blog-section mt-5">
                                    <h3>Edit Blog</h3>
                                    <form method="post" action="{% url 'blogs:blog_detail' slug=blog.slug %}" enctype="multipart/form-data" class="custom-form contact-form" role="form">
                                        {% csrf_token %}
                                        <div class="row">
                                            <div class="col-lg-12 col-md-12 col-12 mb-3">
                                                <div class="form-floating">
                                                    <input type="text" name="title" id="id_title" class="form-control" placeholder="Title" value="{{ blog_form.title.value|default_if_none:'' }}">
                                                    <label for="id_title">Title</label>
{#                                                    {% if blog_form.title.errors %}#}
{#                                                        <div class="invalid-feedback d-block">#}
{#                                                            {{ blog_form.title.errors }}#}
{#                                                        </div>#}
{#                                                    {% endif %}#}
                                                </div>
                                            </div>

                                            <div class="col-lg-12 col-md-12 col-12 mb-3">
                                                <div class="form-floating">
                                                    <input type="text" name="slug" id="id_slug" class="form-control" placeholder="Slug" value="{{ blog_form.slug.value|default_if_none:'' }}">
                                                    <label for="id_slug">Slug</label>
                                                    {% if blog_form.slug.errors %}
                                                        <div class="invalid-feedback d-block">
                                                            {{ blog_form.slug.errors }}
                                                        </div>
                                                    {% endif %}
                                                </div>
                                            </div>

                                            <div class="col-lg-12 col-md-12 col-12 mb-3">
                                                <div class="form-floating">
                                                    <textarea name="body" id="id_body" class="form-control" placeholder="Body">{{ blog_form.body.value|default_if_none:'' }}</textarea>
                                                    <label for="id_body">Body</label>
                                                    {% if blog_form.body.errors %}
                                                        <div class="invalid-feedback d-block">
                                                            {{ blog_form.body.errors }}
                                                        </div>
                                                    {% endif %}
                                                </div>
                                            </div>

                                            <div class="col-lg-12 col-md-12 col-12 mb-3">
                                                <div class="form-floating">
                                                    <input type="file" name="thumbnail" id="id_thumbnail" class="form-control" placeholder="Thumbnail">
                                                    <label for="id_thumbnail">Thumbnail</label>
                                                    {% if blog_form.thumbnail.errors %}
                                                        <div class="invalid-feedback d-block">
                                                            {{ blog_form.thumbnail.errors }}
                                                        </div>
                                                    {% endif %}
                                                </div>
                                            </div>

                                            <input type="hidden" name="form_type" value="blog_form">

                                            <div class="col-lg-4 col-12 ms-auto">
                                                <button type="submit" class="form-control btn btn-primary">Save Changes</button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<!-- Comments Section -->
<div class="comments-section section-padding" id="comments_section">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-12 col-12">
                <div class="section-title-wrap mb-5">
                    <h4 class="section-title">Comments</h4>
                </div>
            </div>

            <div class="col-lg-12 col-12">
                <div class="comments">
                    {% for comment in comments %}
                        <div class="comment mb-4">
                            <div class="card">
                                <div class="card-body">
                                    <p>{{ comment.body }}</p>
                                    <p><strong>{{ comment.author.username }}</strong> - {{ comment.created_at }}</p>
                                    <a href="javascript:void(0);" onclick="toggleReplyForm({{ comment.id }});" class="btn btn-link">Reply</a>

                                    <!-- Main Reply Form -->
                                    <div class="reply-form mt-3 collapse" id="reply-form-{{ comment.id }}">
                                        <form method="post" action="{% url 'blogs:blog_detail' slug=blog.slug %}">
                                            {% csrf_token %}
                                            <div class="form-floating mb-3">
                                                <textarea name="body" id="id_body_{{ comment.id }}" class="form-control" placeholder="Reply">{{ form.body.value|default_if_none:'' }}</textarea>
                                                <label for="id_body_{{ comment.id }}">Reply</label>
                                                {% if form.body.errors %}
                                                    <div class="invalid-feedback d-block">
                                                        {{ form.body.errors }}
                                                    </div>
                                                {% endif %}
                                            </div>
                                            <input type="hidden" name="parent_id" value="{{ comment.id }}">
                                            <input type="hidden" name="form_type" value="comment_form">
                                            <button type="submit" class="btn btn-primary">Reply</button>
                                        </form>
                                    </div>
                                </div>
                            </div>

                            <!-- Display replies -->
                            <div class="replies ms-5 mt-3">
                                {% for reply in comment.replies.all %}
                                    <div class="card reply-card mb-3">
                                        <div class="card-body">
                                            <p>{{ reply.body }}</p>
                                            <p><strong>{{ reply.author.username }}</strong> - {{ reply.created_at }}</p>
                                        </div>
                                    </div>
                                {% endfor %}
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>

            <div class="col-lg-12 col-12 mt-4">
                {% if user.is_authenticated %}
                    <div class="comment-form">
                        <h3>Leave a Comment</h3>
                        <form method="post" action="{% url 'blogs:blog_detail' slug=blog.slug %}">
                            {% csrf_token %}
                            <div class="form-floating mb-3">
                                <textarea name="body" id="id_body" class="form-control" placeholder="Leave a comment">{{ form.body.value|default_if_none:'' }}</textarea>
                                <label for="id_body">Leave a comment</label>
                                {% if form.body.errors %}
                                    <div class="invalid-feedback d-block">
                                        {{ form.body.errors }}
                                    </div>
                                {% endif %}
                            </div>
                            <input type="hidden" name="form_type" value="comment_form">
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </form>
                    </div>
                {% else %}
                    <p>You need to <a href="{% url 'accounts:login' %}">log in</a> to post a comment.</p>
                {% endif %}
            </div>
        </div>
    </div>
</div>
</div>
{% endblock %}