accounts/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views


app_name = 'accounts'

urlpatterns = [
    path('profile/<str:username>/', views.profile_view, name='profile'),
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    # path('password_reset/', name='password_reset'),
    # Password reset views
    path('password_reset/',
         auth_views.PasswordResetView.as_view(template_name='accounts/password_reset_form.html'),
         name='password_reset'),
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),
         name='password_reset_done'),
    # path('password-reset-confirm/<uidb64>/<token>/',
    #      auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html'),
    #      name='password_reset_confirm'),
    # path('password-reset-complete/',
    #      auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),
    #      name='password_reset_complete'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),
         name='password_reset_complete.html'),
    path('clear_cookie_consent_session/', views.clear_cookie_consent_session, name='clear_cookie_consent_session'),
    # path('', include('django.contrib.auth.urls')),
]

blogs/urls.py
"""
URLS - FOR Blogs App
Urls - call the functions in views.py. Views functions contain logic regd. what to send as response.

"""

from django.urls import path
from . import views  # importing views.py from current directory(hence used '.')

app_name = 'blogs'

urlpatterns = [
    path('', views.blogs_list, name='blogs_list'),
    path('create/', views.blog_create, name='blog_create'),
    path('drafts/', views.drafts_list, name='drafts_list'),
    path('load_draft/', views.load_draft, name='load_draft'),

    path('recently_viewed/', views.recently_viewed_blogs, name='recently_viewed_blogs'),
    # below regex: slug can be any character(word, number etc), also includes'-' and length is nolimit.
    path('<slug:slug>/', views.blog_detail, name='blog_detail'),
    path('<slug:slug>/like/', views.like_post, name='like_post'),

]

events/urls.py
# events/urls.py
from django.urls import path
from . import views

app_name = 'events'

urlpatterns = [
    path('add_event/', views.add_event, name='add_event'),
    path('enroll_event/', views.enroll_event, name='enroll_event'),
    path('unenroll_event/', views.unenroll_event, name='unenroll_event'),
    path('my_events/', views.my_events, name='my_events'),
    path('', views.events_list, name='events_list'),
]

gread/urls.py
"""
URLS - FOR Base App - Gread.com
Urls - call the functions in views.py. Views functions contain logic regd. what to send as response.

"""

from django.contrib import admin
from django.urls import path, include  # here include is used to include other urls (from apps)
from . import views  # importing views.py from current directory(hence used '.')
from blogs import views as blogs_views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns  #for loading static files
from django.conf.urls.static import static  #For media Files
from django.conf import settings  #importing all vars and functions from settins.py file
from accounts.admin_site import custom_admin_site

urlpatterns = [
    path('', views.homepage, name='home'),
    # path('', blogs_views.blogs_list, name='home'),
    path('admin/', admin.site.urls),
    # path('admin/', custom_admin_site.urls),
    path('about/', views.about, name='about'),

    # We need to register urls for other apps here in the base urls.py, in order to access them
    path('blogs/', include('blogs.urls')),
    path('accounts/', include('accounts.urls')),
    path("accounts/", include("django.contrib.auth.urls")),
    path('events/', include('events.urls')),

    #     Test Urls
    path('index/', views.index, name='index'),
    path('contact/', views.contact, name='contact'),

]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogs/models.py
"""
1. We do migration so that this class/model (which is an instance of the database table),
is mapped to a db table. -- basically django doesnt know that this class = some table
2. CREATE a Migration file - tracks any changes that we make in any model. -- by running makemigrations
3. ORM bridges gap between code and the database. We can do things like save instance of model,
retrieve model from db etc.

"""

from django.db import models
from django.contrib.auth.models import User
from accounts.models import Member


class Blog(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)  # automatically populate date with this bool value
    thumbnail = models.ImageField(default='default.png', blank=True)
    author = models.ForeignKey(User, default=None, on_delete=models.CASCADE)
    status = models.CharField(max_length=10, choices=[('draft', 'Draft'), ('published', 'Published')],
                              default='published')

    def __str__(self):
        return self.title

    def shorter_body(self):
        return self.body[:70] + "..."


# Model for Comments on Blogs
class Comment(models.Model):
    post = models.ForeignKey(Blog, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    body = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    """
    Note: ForeignKey establishes a one-to-many relationship.
    Hence a single comment can have many replies, but each reply is related to exactly one parent comment.
    """
    parent = models.ForeignKey('self', null=True, blank=True, related_name='replies', on_delete=models.CASCADE)

    def __str__(self):
        return f"Comment by {self.author} on {self.post}"

    @property
    def is_reply(self):
        return self.parent is not None


# Model for Likes on Blogs
class Like(models.Model):
    post = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name='likes')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('post', 'user')

    def __str__(self):
        return f"{self.user} likes {self.post}"

templates/about.html
{% extends 'base_layout.html' %}
{% load static %}
{% block title %} Gread - About {% endblock %}
{% block content %}
    <header class="site-header d-flex flex-column justify-content-center align-items-center">
        <div class="container">
            <div class="row">

                <div class="col-lg-12 col-12 text-center">

                    <h2 class="mb-0">About GRead</h2>
                </div>

            </div>
        </div>
    </header>

    <section class="about-section section-padding" id="section_2">
        <div class="container">
            <div class="row gy-4">

                <div class="col-lg-8 col-12 mx-auto">
                    <div class="pb-5 mb-5">
                        <div class="section-title-wrap mb-4">
                            <h4 class="section-title">Our story</h4>
                        </div>
                        <p>Gread aims to significantly contribute to environmental
                        awareness and advocacy. By providing a dedicated platform for sharing
                        green-related content, we aim to facilitate the dissemination of crucial
                            information on environmental issues, sustainable practices, and eco-friendly innovations.</p>

                        <p>Users can share their experiences, tips, and knowledge, fostering a community of like-minded
                        individuals committed to environmental preservation. This collective effort will help raise awareness,
                            inspire action, and promote sustainable living practices.</p>
                        <p>Additionally, by highlighting green initiatives
                        and success stories, our platform will motivate others to adopt
                            environmentally friendly habits, ultimately contributing to a healthier and more sustainable planet.</p>

                        <img src="{% static 'images/about_intro.jpg' %}" class="about-image mt-5 img-fluid" alt="">
                    </div>
                </div>

                <div class="col-lg-12 col-12">
                    <div class="section-title-wrap mb-5">
                        <h4 class="section-title">Meet creators</h4>
                    </div>
                </div>

                <div class="col-lg-3 col-md-6 col-12 mb-4 mb-lg-0">
                    <div class="team-thumb bg-white shadow-lg">
                        <img src="{% static 'images/profile/profile_default.png' %}" class="about-image img-fluid" alt="">
<br><br><br><br><br><br>
                        <div class="team-info">
                            <h4 class="mb-2">
                                Abdul Rahman
                                <img src="{% static 'images/verified.png' %}" class="verified-image img-fluid" alt="">
                            </h4>

                            <span class="badge">Tech</span>
                            <span class="badge">Fitness</span>
                        </div>

                        <div class="social-share">
                            <ul class="social-icon">
                                <li class="social-icon-item">
                                    <a href="#" class="social-icon-link bi-twitter"></a>
                                </li>
                                <li class="social-icon-item">
                                    <a href="#" class="social-icon-link bi-facebook"></a>
                                </li>
                                <li class="social-icon-item">
                                    <a href="#" class="social-icon-link bi-linkedin"></a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>

                <div class="col-lg-3 col-md-6 col-12 mb-4 mb-lg-0">
                    <div class="team-thumb bg-white shadow-lg">
                        <img src="{% static 'images/profile/profile_default.png' %}" class="about-image img-fluid" alt="">
<br><br><br><br><br><br>
                        <div class="team-info">
                            <h4 class="mb-2">
                                Meet
                                <img src="{% static 'images/verified.png' %}" class="verified-image img-fluid" alt="">
                            </h4>

                            <span class="badge">Creative</span>
                            <span class="badge">Design</span>
                        </div>

                        <div class="social-share">
                            <ul class="social-icon">
                                <li class="social-icon-item">
                                    <a href="#" class="social-icon-link bi-twitter"></a>
                                </li>
                                <li class="social-icon-item">
                                    <a href="#" class="social-icon-link bi-facebook"></a>
                                </li>
                                <li class="social-icon-item">
                                    <a href="#" class="social-icon-link bi-linkedin"></a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>

                <div class="col-lg-3 col-md-6 col-12 mb-4 mb-lg-0 mb-md-0">
                    <div class="team-thumb bg-white shadow-lg">
                        <img src="{% static 'images/profile/profile_default.png' %}" class="about-image img-fluid" alt="">
<br><br><br><br><br><br>
                        <div class="team-info">
                            <h4 class="mb-2">
                                Mihir
                                <img src="{% static 'images/verified.png' %}" class="verified-image img-fluid" alt="">
                            </h4>

                            <span class="badge">Documentation</span>
                        </div>

                        <div class="social-share">
                            <ul class="social-icon">
                                <li class="social-icon-item">
                                    <a href="#" class="social-icon-link bi-linkedin"></a>
                                </li>
                                <li class="social-icon-item">
                                    <a href="#" class="social-icon-link bi-instagram"></a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>

                <div class="col-lg-3 col-md-6 col-12">
                    <div class="team-thumb bg-white shadow-lg">
                        <img src="{% static 'images/profile/profile_default.png' %}" class="about-image img-fluid" alt="">
<br><br><br><br><br><br>
                        <div class="team-info">
                            <h4 class="mb-2">
                                Vaibhav
                                <img src="{% static 'images/verified.png' %}" class="verified-image img-fluid" alt="">
                            </h4>

                            <span class="badge">Development</span>
                            <span class="badge">Business</span>
                        </div>

                        <div class="social-share">
                            <ul class="social-icon">
                                <li class="social-icon-item">
                                    <a href="#" class="social-icon-link bi-twitter"></a>
                                </li>
                                <li class="social-icon-item">
                                    <a href="#" class="social-icon-link bi-facebook"></a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>

                <div class="col-lg-3 col-md-6 col-12 mb-4 mb-lg-0"></div>

                <div class="col-lg-3 col-md-6 col-12 mb-4 mb-lg-0">
                    <div class="team-thumb bg-white shadow-lg">
                        <img src="{% static 'images/profile/profile_default.png' %}" class="about-image img-fluid" alt="">
<br><br><br><br><br><br>
                        <div class="team-info">
                            <h4 class="mb-2">
                                Kandarp
                                <img src="{% static 'images/verified.png' %}" class="verified-image img-fluid" alt="">
                            </h4>

                            <span class="badge">Development</span>
                            <span class="badge">Business</span>
                        </div>

                        <div class="social-share">
                            <ul class="social-icon">
                                <li class="social-icon-item">
                                    <a href="#" class="social-icon-link bi-twitter"></a>
                                </li>
                                <li class="social-icon-item">
                                    <a href="#" class="social-icon-link bi-facebook"></a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>

                <div class="col-lg-3 col-md-6 col-12 mb-4 mb-lg-0 mb-md-0"></div>
                <div class="col-lg-3 col-md-6 col-12"></div>

            </div>
        </div>
    </section>
{% endblock %}

templates/contact.html
{% extends 'base_layout.html' %}
{% load static %}
{% block title %} Gread - Contact {% endblock %}
{% block content %}
    <header class="site-header d-flex flex-column justify-content-center align-items-center">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-12 text-center">
                    <h2 class="mb-0">Contact Us</h2>
                </div>
            </div>
        </div>
    </header>

    <section class="section-padding" id="section_2">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-5 col-12 pe-lg-5">
                    <div class="contact-info">
                        <h3 class="mb-4">We love to help you. Get in touch</h3>
                        <p class="d-flex border-bottom pb-3 mb-4">
                            <strong class="d-inline me-4">Phone:</strong>
                            <span>226-988-9999</span>
                        </p>
                        <p class="d-flex border-bottom pb-3 mb-4">
                            <strong class="d-inline me-4">Email:</strong>
                            <a href="mailto:inquiry@pod.co">inquiry@gread.com</a>
                        </p>
                        <p class="d-flex">
                            <strong class="d-inline me-4">Location:</strong>
                            <span>401 Sunset Ave, Windsor, ON N9B 3P4</span>
                        </p>
                    </div>
                </div>
                <div class="col-lg-5 col-12 mt-5 mt-lg-0">
                    <iframe class="google-map"
                        src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3988.819917806043!2d103.84793601429608!3d1.281807962148459!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x31da190c2c94ccb3%3A0x11213560829baa05!2sTwitter!5e0!3m2!1sen!2smy!4v1669212183861!5m2!1sen!2smy"
                        width="100%" height="300" style="border:0;" allowfullscreen="" loading="lazy"
                        referrerpolicy="no-referrer-when-downgrade"></iframe>
                </div>
            </div>
        </div>
    </section>

    <section class="contact-section section-padding pt-0">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-12 mx-auto">
                    <div class="section-title-wrap mb-5">
                        <h4 class="section-title">You know, Contact Form</h4>
                    </div>

                    <form action="#" method="post" class="custom-form contact-form" role="form">
                        <div class="row">
                            <div class="col-lg-6 col-md-6 col-12">
                                <div class="form-floating">
                                    <input type="text" name="full-name" id="full-name" class="form-control"
                                        placeholder="Full Name" required="">
                                    <label for="full-name">Full Name</label>
                                </div>
                            </div>

                            <div class="col-lg-6 col-md-6 col-12">
                                <div class="form-floating">
                                    <input type="email" name="email" id="email" pattern="[^ @]*@[^ @]*"
                                        class="form-control" placeholder="Email address" required="">
                                    <label for="email">Email address</label>
                                </div>
                            </div>

                            <div class="col-lg-12 col-12">
                                <div class="form-floating">
                                    <input type="text" name="company" id="company" class="form-control"
                                        placeholder="Company" required="">
                                    <label for="company">Company</label>
                                </div>

                                <div class="form-floating">
                                    <textarea class="form-control" id="message" name="message"
                                        placeholder="Describe message here"></textarea>
                                    <label for="message">Describe message here</label>
                                </div>
                            </div>

                            <div class="col-lg-4 col-12 ms-auto">
                                <button type="submit" class="form-control">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

templates/homepage.html
{% extends 'base_layout.html' %}

{% block title %} Gread - Home {% endblock %}
{% load static %}
{% block content %}
    <!-- user variable - the user object from the session, managed by Django's auth system. 
    This object is initially retrieved from the database when the user logs in
     and is referenced in the session thereafter. -->
<!-- Opening Section & profiles -->
    <section class="hero-section">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 col-12">
                <div class="text-center mb-5 pb-2">
                    <h1 class="text-white">Welcome to GRead{% if user.is_authenticated %}, {{ user }}{% endif %}</h1>
                    <p class="text-white">Sustainability for All. Explore your fav events & blogs.</p>
                    <a href="#section_2" class="btn custom-btn smoothscroll mt-3">Start exploring</a>
                </div>

                <div class="owl-carousel owl-theme">
                    {% for item in member_tags %}
                    <div class="owl-carousel-info-wrap item">
{#                    <a href="{% url 'accounts:profile' item.member.user.username %}">#}
                         <img src="{{ item.member.profile_picture.url }}" class="owl-carousel-image img-fluid" 
                              style="height: 400px; object-fit: cover; width: 100%;" alt="{{ item.member.user.username }}"
                                onclick="redirectToProfile('{{ item.member.user.username }}')">
{#                    </a>#}
                        <div class="owl-carousel-info">
                            <h4 class="mb-2">
                                {{ item.member.user.username }}
                                <img src="../static/images/verified.png" class="owl-carousel-verified-image img-fluid" alt="Verified">
                            </h4>

                            <span class="badge">{{ item.tag }}</span>
                        </div>

                        <div class="social-share">
                            <ul class="social-icon">
                                <li class="social-icon-item">
                                    <a href="#" class="social-icon-link bi-twitter"></a>
                                </li>
                                <li class="social-icon-item">
                                    <a href="#" class="social-icon-link bi-facebook"></a>
                                </li>
                                <!-- Add more social links as needed -->
                            </ul>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            <script>
    function redirectToProfile(username) {
        window.location.href = `/accounts/profile/${username}/`;
    }
</script>
            </div>
        </div>
    </div>
</section>
<!-- Trending Blogs -- MOST Liked Section -->
    <section class="trending-podcast-section section-padding pb-0">
    <div class="container">
        <div class="row gy-4">
            <div class="col-lg-12 col-12">
                <div class="section-title-wrap mb-5">
                    <h4 class="section-title">Trending Topics</h4>
                </div>
            </div>

            {% for blog in most_liked_blogs %}
            <div class="col-lg-4 col-12 mb-4 mb-lg-0">
                <div class="custom-block custom-block-full">
                    <div class="custom-block-image-wrap">
                        <a href="{% url 'blogs:blog_detail' blog.slug %}">
                            <img src="{{ blog.thumbnail.url }}" class="custom-block-image img-fluid" alt="{{ blog.title }}">
                        </a>
                    </div>

                    <div class="custom-block-info">
                        <h5 class="mb-2">
                            <a href="{% url 'blogs:blog_detail' blog.slug %}">
                                {{ blog.title }}
                            </a>
                        </h5>

                        <div class="profile-block d-flex">
                                <img src="{% static 'images/verified.png' %}" class="verified-image-blogs img-fluid" alt="">
                            <a href="{% url 'accounts:profile' blog.author.username %}">
                                <p>
                                {{ blog.author.username }}
                                <strong>{{ blog.author.get_profile_type_display }}</strong>
                            </p>
                            </a>

                        </div>

                        <p class="mb-0">{{ blog.shorter_body }}</p>

                        <div class="custom-block-bottom d-flex justify-content-between mt-3">
                            <a href="#" class="bi-heart me-1">
                                <span>{{ blog.like_set.count }}</span>
                            </a>
                        </div>
                    </div>

                    <div class="social-share d-flex flex-column ms-auto">
                        <a href="#" class="badge ms-auto">
                            <i class="bi-heart"></i>
                        </a>

                        <a href="#" class="badge ms-auto">
                            <i class="bi-bookmark"></i>
                        </a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>
<!-- Upcoming Events Section -->
    <section class="topics-section section-padding pb-0" id="section_3">
    <div class="container">
        <div class="row gy-4">
            <div class="col-lg-12 col-12">
                <div class="section-title-wrap mb-5">
                    <h4 class="section-title">Events</h4>
                </div>
            </div>

            {% for event in recent_events %}
            <div class="col-lg-3 col-md-6 col-12 mb-4 mb-lg-0">
                <div class="custom-block custom-block-overlay">
                    <a href="{% url 'events:events_list' %}" class="custom-block-image-wrap">
                        <img src="{{ event.event_banner.url }}" class="custom-block-image img-fluid" alt="{{ event.title }}">
                    </a>

                    <div class="custom-block-info custom-block-overlay-info">
                        <h5 class="mb-1">
                            <a href="{% url 'events:events_list' %}">
                                {{ event.title }}
                            </a>
                        </h5>
                        <p class="badge mb-0">{{ event.datetime|date:"F j, Y, g:i a" }}</p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>
<!-- Latest Blogs Section -->
    <section class="latest-podcast-section section-padding" id="section_2">
    <div class="container">
        <div class="row justify-content-center gy-4">
            <div class="col-lg-12 col-12">
                <div class="section-title-wrap mb-5">
                    <h4 class="section-title">Latest Blogs</h4>
                </div>
            </div>

            {% for blog in latest_blogs %}
            <div class="col-lg-6 col-12 mb-4 mb-lg-0">
                <div class="custom-block d-flex">
                    <div class="">
                        <div class="custom-block-icon-wrap">
                            <div class="section-overlay"></div>
                            <a href="{% url 'blogs:blog_detail' blog.slug %}" class="custom-block-image-wrap">
                                <img src="{{ blog.thumbnail.url }}" class="custom-block-image img-fluid" alt="{{ blog.title }}">

                                <a href="{% url 'blogs:blog_detail' blog.slug %}" class="custom-block-icon">
                                    <i class="bi-play-fill"></i>
                                </a>
                            </a>
                        </div>

                        <div class="mt-2">
                            <a href="#" class="btn custom-btn">
                                View
                            </a>
                        </div>
                    </div>

                    <div class="custom-block-info">
                        <h5 class="mb-2">
                            <a href="{% url 'blogs:blog_detail' blog.slug %}">
                                {{ blog.title }}
                            </a>
                        </h5>

                        <div class="profile-block d-flex">
                            <img src="{% static 'images/verified.png' %}" class="verified-image-blogs img-fluid" alt="">
                            <a href="{% url 'accounts:profile' blog.author.username %}">
                                <p>
                                {{ blog.author.username }}
                                <strong>{{ blog.author.get_profile_type_display }}</strong>
                            </p>
                        </div>

                        <p class="mb-0">{{ blog.shorter_body }}</p>

                        <div class="custom-block-bottom d-flex justify-content-between mt-3">
                            <a href="#" class="bi-heart me-1">
                                <span>{{ blog.like_set.count }}</span>
                            </a>
                        </div>
                    </div>

                    <div class="d-flex flex-column ms-auto">
                        <a href="#" class="badge ms-auto">
                            <i class="bi-heart"></i>
                        </a>

                        <a href="#" class="badge ms-auto">
                            <i class="bi-bookmark"></i>
                        </a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>

{% endblock %}